/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2014-08-13 06:50:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user.jsp_0020files.afterlogin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class afterlogin_005findex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/user/jsp files/checksession.jsp", Long.valueOf(1407909381372L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/vision/user/css files/slider.css\"  />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/vision/user/css files/grid.css\" />\r\n");
      out.write("<script src=\"/vision/user/js files/grid.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"/vision/user/js files/slider.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");


String usernm = (String) session.getAttribute("username");
if(usernm==null)
	response.sendRedirect("/vision/user/jsp files/index/login_signup.jsp");

      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<title>Untitled Document</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* hover menu*/\r\n");
      out.write("#indiv tr td a\r\n");
      out.write("{\r\n");
      out.write("    float: left;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 160px;\r\n");
      out.write("\theight: 60px;\r\n");
      out.write("\tpadding: 20px 0px 0 0px;\r\n");
      out.write("\tmargin: 0px 10px 0px 10px ;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor:Black;\t\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#indiv tr td a:hover,#indiv tr td .current\r\n");
      out.write("{\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  background: Black ;\r\n");
      out.write("  color: Orange; \r\n");
      out.write("}\t\r\n");
      out.write("\r\n");
      out.write("#indiv tr td ul li ul li a:hover\r\n");
      out.write("{\r\n");
      out.write("  background:none;\r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write("  color: White; \r\n");
      out.write("}\r\n");
      out.write("/* drop down menu*/\r\n");
      out.write("/*body {\r\n");
      out.write("  font-family: 'Lucida Grande', 'Helvetica Neue', Helvetica, Arial, sans-serif;\r\n");
      out.write("  padding: 20px 50px 150px;\r\n");
      out.write("  font-size: 13px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  background: #E3CAA1;\r\n");
      out.write("}*/\r\n");
      out.write("\r\n");
      out.write("#dropdown ul {\r\n");
      out.write("  text-align: left;\r\n");
      out.write("  display: inline;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 45px 10px 17px 5px;\r\n");
      out.write("  list-style: none;\r\n");
      out.write("  /*-webkit-box-shadow: 0 0 5px rgba(0, 0, 0, 0.15);\r\n");
      out.write("  -moz-box-shadow: 0 0 5px rgba(0, 0, 0, 0.15);\r\n");
      out.write("  box-shadow: 0 0 5px rgba(0, 0, 0, 0.15);*/\r\n");
      out.write("}\r\n");
      out.write("#dropdown ul li {\r\n");
      out.write("  font: bold 16px/16px sans-serif;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  margin-right: 5px;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  padding: 10px 15px;\r\n");
      out.write("  background: rgba(213, 35, 35, 0.67);\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  -webkit-transition: all 0.2s;\r\n");
      out.write("  -moz-transition: all 0.2s;\r\n");
      out.write("  -ms-transition: all 0.2s;\r\n");
      out.write("  -o-transition: all 0.2s;\r\n");
      out.write("  transition: all 0.2s;\r\n");
      out.write("}\r\n");
      out.write("#dropdown ul li:hover {\r\n");
      out.write("  background: rgba(213, 35, 35, 0.67);\r\n");
      out.write("  color: #fff;\r\n");
      out.write("}\r\n");
      out.write("#dropdown ul li ul {\r\n");
      out.write("  padding: 0px;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 52px;\r\n");
      out.write("  left: 0px;\r\n");
      out.write("  width: 130px;\r\n");
      out.write("  /*-webkit-box-shadow: none;\r\n");
      out.write("  -moz-box-shadow: none;\r\n");
      out.write("  box-shadow: none;*/\r\n");
      out.write("  display: none;\r\n");
      out.write("  opacity: 0;\r\n");
      out.write("  visibility: hidden;\r\n");
      out.write("  -webkit-transiton: opacity 0.2s;\r\n");
      out.write("  -moz-transition: opacity 0.2s;\r\n");
      out.write("  -ms-transition: opacity 0.2s;\r\n");
      out.write("  -o-transition: opacity 0.2s;\r\n");
      out.write("  -transition: opacity 0.2s;\r\n");
      out.write("}\r\n");
      out.write("#dropdown ul li ul li { \r\n");
      out.write("  background: rgba(199, 89, 38, 0.67);\r\n");
      out.write("  display: block; \r\n");
      out.write("  color: #fff;\r\n");
      out.write("  //text-shadow: 0 -1px 0 #000;\r\n");
      out.write("}\r\n");
      out.write("#dropdown ul li ul li:hover \r\n");
      out.write("{ background: rgba(199, 89, 38, 0.67);display: none;\r\n");
      out.write("}\r\n");
      out.write("#dropdown ul li:hover ul {\r\n");
      out.write("  display: block;\r\n");
      out.write("  opacity: 1;\r\n");
      out.write("  visibility: visible;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"background:url(/vision/user/images/background/parquet_flooring-1920x1200.jpg);background-size: cover \">\r\n");
      out.write("<table  align=\"center\" width=\"100%\">\r\n");
      out.write(" <tr height=\"40\">\r\n");
      out.write("  <td>\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr height='50' >\r\n");
      out.write("  <td>\r\n");
      out.write("   <table id='indiv' align=\"center\"><!--table 2 inside table 1-->\r\n");
      out.write("     <tr>\r\n");
      out.write("\t  <td><a href='/vision/user/jsp files/afterlogin/afterlogin_index.jsp' target='_top' class='current'>HOME</a></td>\r\n");
      out.write("      <td><a href='/vision/user/jsp files/index/about_us.jsp' target='_top'>ABOUT US</a></td>\r\n");
      out.write("      <td><a href='/vision/user/jsp files/index/contact_us.jsp' target='_top'>CONTACT US</a></td>\r\n");
      out.write("      <td><a href='/vision/user/jsp files/afterlogin/afterlogin_information.jsp' target='_parent'>INFORMATION RESOURCE</a></td>\r\n");
      out.write("      <td><a href='/vision/user/jsp files/afterlogin/feedback.jsp' target='_parent'>FEEDBACK</a></td>\r\n");
      out.write("      <td><a href='/vision/user/jsp files/afterlogin/afterlogin_features.jsp' target='_parent'>FEATURES</a></td>\r\n");
      out.write("      <td><img src='/vision/user/images/loginform/user1.png'></img></td>\r\n");
      out.write("\t  <td id=dropdown>\r\n");
      out.write("\t   <ul>\r\n");
      out.write("\t    <li style=\"width: 113px;height: 52px\">\r\n");
      out.write("        Hi, ");
String usrname=(String) session.getAttribute("username");
      out.print(usrname );
      out.write("\r\n");
      out.write("\t\t <ul>\r\n");
      out.write("          <li style=\"float: left;display: inherit; \" ><a href='/vision/LogoutServlet' style=\"font-size: inherit;text-align: left;  width: 63px; height:32px; \">Log Out</a></li>\r\n");
      out.write("     \t <li style=\"float: left;display: inherit; \"><a href='/vision/UpdateServlet' style=\"font-size: inherit;text-align: left; width: 108px; height: 31px \">Update profile</a></li>\r\n");
      out.write("\t\t </ul>\t\t\t\t\t\t\t\t\r\n");
      out.write(" \t\t</li>\t\t\t    \r\n");
      out.write("       </ul>         \r\n");
      out.write("      </td>                  \r\n");
      out.write("    \t\t\t\t  \r\n");
      out.write("\t </tr>\t\t\t   \r\n");
      out.write("    </table><!--end of table 2-->                  \r\n");
      out.write("   </td>       \t            \r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr height='54'>\r\n");
      out.write("   <td>\r\n");
      out.write("   </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr height='530'>\r\n");
      out.write("   <td>\r\n");
      out.write("   \r\n");
      out.write("   <div id=\"sliderFrame\">\r\n");
      out.write("        <div id=\"slider\">\r\n");
      out.write("            <img src=\"/vision/user/images/slider/DSC02654-qpr.jpg\" />\r\n");
      out.write("            <img src=\"/vision/user/images/slider/DSC01672-qpr.jpg\" />\r\n");
      out.write("            <img src=\"/vision/user/images/slider/DSC02647-qpr.jpg\" />\r\n");
      out.write("            <img src=\"/vision/user/images/slider/DSC00619-qpr.jpg\" />\r\n");
      out.write("            <img src=\"/vision/user/images/slider/DSC00779-qpr.jpg\" />\r\n");
      out.write("            <img src=\"/vision/user/images/slider/DSC00780-qpr.jpg\" />\r\n");
      out.write("\t\t\t<img src=\"/vision/user/images/slider/DSC00792-qpr.jpg\" />\r\n");
      out.write("\t\t\t<img src=\"/vision/user/images/slider/DSC00804-qpr.jpg\" />\r\n");
      out.write("\t\t\t<img src=\"/vision/user/images/slider/DSC00834-qpr.jpg\" />\r\n");
      out.write("\t\t\t<img src=\"/vision/user/images/slider/DSC01215-qpr.jpg\" />\r\n");
      out.write("\t\t\t<img src=\"/vision/user/images/slider/DSC02603-qpr.jpg\" />\r\n");
      out.write("\t\t\t<img src=\"/vision/user/images/slider/DSC_1164-qpr.jpg\" />\r\n");
      out.write("\t\t\t<img src=\"/vision/user/images/slider/DSC02639-qpr.jpg\" />\r\n");
      out.write("\t\t\t\r\n");
      out.write("            \r\n");
      out.write("\t\t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("   \r\n");
      out.write("   </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("   <td>\r\n");
      out.write("    <div class=\"container demo-2\">\r\n");
      out.write("\t\t\t<ul class=\"grid cs-style-2\">\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<figure>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/vision/user/images/grid/2.gif\" style=\"height: 250px;width: 500px\"/>\r\n");
      out.write("\t\t\t\t\t\t<figcaption>\r\n");
      out.write("\t\t\t\t\t\t\t<h3>WILDLIFE SANCTUARIES</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/vision/user/jsp files/wildlife/wildlife.jsp\">Take a look</a>\r\n");
      out.write("\t\t\t\t\t\t</figcaption>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t  </figure>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<figure>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/vision/user/images/grid/4.jpg\" style=\"height: 250px;width: 500px\"/>\r\n");
      out.write("\t\t\t\t\t\t<figcaption>\r\n");
      out.write("\t\t\t\t\t\t\t<h3>MUSEUMS</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/vision/user/jsp files/museums/museums.jsp\">Take a look</a>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</figcaption>\t\r\n");
      out.write("\t\t\t\t  </figure>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<figure>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/vision/user/images/grid/1.jpg\" style=\"height: 250px;width: 500px\"/>\r\n");
      out.write("\t\t\t\t\t\t<figcaption>\r\n");
      out.write("\t\t\t\t\t\t\t<h3>HOTELS</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/vision/user/jsp files/hotels/hotels.jsp\">Take a look</a>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</figcaption>\r\n");
      out.write("\t\t\t\t  </figure>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<figure>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/vision/user/images/grid/5.jpg\" style=\"height: 250px;width: 500px\"/>\r\n");
      out.write("\t\t\t\t\t\t<figcaption>\r\n");
      out.write("\t\t\t\t\t\t\t<h3>RESTAURANTS</h3>\r\n");
      out.write("\t\t\t\t\t\t    <a href=\"/vision/user/jsp files/restaurants/restaurants.jsp\">Take a look</a>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</figcaption>\r\n");
      out.write("\t\t\t\t  </figure>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<figure>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/vision/user/images/grid/3.jpg\" style=\"height: 250px;width: 500px\"/>\r\n");
      out.write("\t\t\t\t\t\t<figcaption>\r\n");
      out.write("\t\t\t\t\t\t\t<h3>EXCURSIONS OF UDAIPUR</h3>\r\n");
      out.write("\t\t\t\t\t\t    <a href=\"/vision/user/jsp files/excursions/excursion.jsp\">Take a look</a>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</figcaption>\r\n");
      out.write("\t\t\t\t  </figure>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<figure>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/vision/user/images/grid/6.jpg\" style=\"height: 250px;width: 500px\"/>\r\n");
      out.write("\t\t\t\t\t\t<figcaption>\r\n");
      out.write("\t\t\t\t\t\t\t<h3>TEMPLES</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/vision/user/jsp files/temples/temples.jsp\">Take a look</a>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</figcaption>\r\n");
      out.write("\t\t\t\t  </figure>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("    </div><!-- /container -->\r\n");
      out.write("\t\t<!--<script src=\"js/toucheffects.js\"></script>-->\r\n");
      out.write("\r\n");
      out.write("   </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  \r\n");
      out.write("  </table><!-- end of table 1-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
