/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2014-08-13 05:56:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user.jsp_0020files.temples;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class temples_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/user/jsp files/checksession.jsp", Long.valueOf(1407909381372L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");


String usernm = (String) session.getAttribute("username");
if(usernm==null)
	response.sendRedirect("/vision/user/jsp files/index/login_signup.jsp");

      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<script src=\"/vision/user/js files/scroll.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("/* hover menu*/\r\n");
      out.write("#indiv tr td a\r\n");
      out.write("{\r\n");
      out.write("    float: left;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 160px;\r\n");
      out.write("\theight: 45px;\r\n");
      out.write("\tpadding: 20px 0px 0 0px;\r\n");
      out.write("\tmargin: 0px 10px 0px 10px ;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor:Black;\t\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#indiv tr td a:hover,#indiv tr td .current\r\n");
      out.write("{\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  background: Black ;\r\n");
      out.write("  color: Orange; \r\n");
      out.write("}\t\r\n");
      out.write("\r\n");
      out.write("#indiv tr td ul li ul li a:hover\r\n");
      out.write("{\r\n");
      out.write("  background:none;\r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write("  color: White; \r\n");
      out.write("}\r\n");
      out.write("/* drop down menu*/\r\n");
      out.write("/*body {\r\n");
      out.write("  font-family: 'Lucida Grande', 'Helvetica Neue', Helvetica, Arial, sans-serif;\r\n");
      out.write("  padding: 20px 50px 150px;\r\n");
      out.write("  font-size: 13px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  background: #E3CAA1;\r\n");
      out.write("}*/\r\n");
      out.write("\r\n");
      out.write("#dropdown ul {\r\n");
      out.write("  text-align: left;\r\n");
      out.write("  display: inline;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 45px 10px 17px 5px;\r\n");
      out.write("  list-style: none;\r\n");
      out.write("  /*-webkit-box-shadow: 0 0 5px rgba(0, 0, 0, 0.15);\r\n");
      out.write("  -moz-box-shadow: 0 0 5px rgba(0, 0, 0, 0.15);\r\n");
      out.write("  box-shadow: 0 0 5px rgba(0, 0, 0, 0.15);*/\r\n");
      out.write("}\r\n");
      out.write("#dropdown ul li {\r\n");
      out.write("  font: bold 16px/16px sans-serif;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  margin-right: 5px;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  padding: 10px 15px;\r\n");
      out.write("  background: rgba(213, 35, 35, 0.67);\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  -webkit-transition: all 0.2s;\r\n");
      out.write("  -moz-transition: all 0.2s;\r\n");
      out.write("  -ms-transition: all 0.2s;\r\n");
      out.write("  -o-transition: all 0.2s;\r\n");
      out.write("  transition: all 0.2s;\r\n");
      out.write("}\r\n");
      out.write("#dropdown ul li:hover {\r\n");
      out.write("  background: rgba(213, 35, 35, 0.67);\r\n");
      out.write("  color: #fff;\r\n");
      out.write("}\r\n");
      out.write("#dropdown ul li ul {\r\n");
      out.write("  padding: 0px;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 52px;\r\n");
      out.write("  left: 0px;\r\n");
      out.write("  width: 130px;\r\n");
      out.write("  /*-webkit-box-shadow: none;\r\n");
      out.write("  -moz-box-shadow: none;\r\n");
      out.write("  box-shadow: none;*/\r\n");
      out.write("  display: none;\r\n");
      out.write("  opacity: 0;\r\n");
      out.write("  visibility: hidden;\r\n");
      out.write("  -webkit-transiton: opacity 0.2s;\r\n");
      out.write("  -moz-transition: opacity 0.2s;\r\n");
      out.write("  -ms-transition: opacity 0.2s;\r\n");
      out.write("  -o-transition: opacity 0.2s;\r\n");
      out.write("  -transition: opacity 0.2s;\r\n");
      out.write("}\r\n");
      out.write("#dropdown ul li ul li { \r\n");
      out.write("  background: rgba(199, 89, 38, 0.67);\r\n");
      out.write("  display: block; \r\n");
      out.write("  color: #fff;\r\n");
      out.write("  //text-shadow: 0 -1px 0 #000;\r\n");
      out.write("}\r\n");
      out.write("#dropdown ul li ul li:hover \r\n");
      out.write("{ background: rgba(199, 89, 38, 0.67);display: none;\r\n");
      out.write("}\r\n");
      out.write("#dropdown ul li:hover ul {\r\n");
      out.write("  display: block;\r\n");
      out.write("  opacity: 1;\r\n");
      out.write("  visibility: visible;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"background:url(/vision/user/images/background/parquet_flooring-1920x1200.jpg); background-size: cover; \">\r\n");
      out.write("<table  align=\"center\" width=\"70%\">\r\n");
      out.write(" <tr height=\"40\">\r\n");
      out.write("  <td>\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr height='50' >\r\n");
      out.write(" <td>\r\n");
      out.write("   <table  id='indiv' align=\"center\"><!--table 2 inside table 1-->\r\n");
      out.write("     <tr>\r\n");
      out.write("\t  <td><a href='/vision/user/jsp files/afterlogin/afterlogin_index.jsp' target='_parent'>HOME</a></td>\r\n");
      out.write("      <td><a href='/vision/user/jsp files/about_us.jsp' target='_parent'>ABOUT US</a></td>\r\n");
      out.write("      <td><a href='/vision/user/jsp files/contact_us.jsp' target='_parent'>CONTACT US</a></td>\r\n");
      out.write("      <td><a href='/vision/user/jsp files/afterlogin/afterlogin_information.jsp' target='_parent'>INFORMATION RESOURCE</a></td>\r\n");
      out.write("      <td><a href='/vision/user/jsp files/afterlogin/feedback.jsp' target='_parent'>FEEDBACK</a></td>\r\n");
      out.write("      <td><a href='/vision/user/jsp files/afterlogin/afterlogin_features.jsp' target='_top'class='current'>FEATURES</a></td>\r\n");
      out.write("      <td><img src='/vision/user/images/loginform/user1.png'></img></td>\r\n");
      out.write("\t  <td id=dropdown>\r\n");
      out.write("\t   <ul >\r\n");
      out.write("\t    <li style=\"width: 83px;height: 33px\">\r\n");
      out.write("        Hi, ");
String usrname=(String) session.getAttribute("username");
      out.print(usrname );
      out.write("\r\n");
      out.write("\t\t <ul>\r\n");
      out.write("          <li style=\"float: left;display: inherit; \" ><a href='/vision/LogoutServlet' style=\"font-size: inherit;text-align: left;  width: 63px; height: 8px; \">Log Out</a></li>\r\n");
      out.write("     \t  <li style=\"float: left;display: inherit; \"><a href='/vision/UpdateServlet' style=\"font-size: inherit;text-align: left; width: 107px; height: 17px \">Update profile</a></li>\r\n");
      out.write("\t\t </ul>\t\t\t\t\t\t\t\t\r\n");
      out.write(" \t\t</li>\t\t\t    \r\n");
      out.write("       </ul>         \r\n");
      out.write("      </td>                  \r\n");
      out.write("    \t\t\t\t  \r\n");
      out.write("\t </tr>\r\n");
      out.write("\t\t\t   \r\n");
      out.write("    </table><!--end of table 2-->                  \r\n");
      out.write("   </td>       \t            \r\n");
      out.write("  </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("  <td>\r\n");
      out.write("   <a name=\"top\"></a>\r\n");
      out.write("   <p style=\"font-family: cursive;font-size: x-large;font-weight: bold;color: Orange\">Famous Temples In and Around Udaipur</p><br/>\r\n");
      out.write("   <p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\">Most of us are unaware that Udaipur is also famous for its temples. \r\n");
      out.write("   These temples are visited by several thousand tourists every year. Many tourists visit these temples regularly. \r\n");
      out.write("   The vibrant and marvelous historical background of Mewar region reveals that many of these temples were built by the emperors of Mewar dynasty. \r\n");
      out.write("   Throughout the history; the emperors of Mewar had showcased a blend of courage and spirituality. \r\n");
      out.write("   These are few famous temples of Udaipur and their small stories behind their construction.</p><br/>\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("  <td>\r\n");
      out.write("   <p style=\"font-family: cursive;font-size: x-large;font-weight: bold;color: Orange\">1. Bohra Ganesh Temple</p><br/>\r\n");
      out.write("   <img src=\"/vision/user/images/temples/bohraganeshji.jpg\" />\r\n");
      out.write("   <p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\">Bohra Ganesh Ji a very old and famous temple of Udaipur is situated near Mohanlal Sukhadia University. \r\n");
      out.write("    A standing statue of Shri Ganesh Ji has been established which bestow blessings to hundreds of devotees visiting every day.\r\n");
      out.write("    In India it is a custom to worship Lord Ganesh whenever something new is started like new business, new asset or starting a new relationship. \r\n");
      out.write("    Wednesday is considered as the special day to worship Lord Ganesha. Thousands of devotees visit Bohra Ganesh Ji temple to offer Prayer and Prasad (Sweets) to Shri Ganesh Ji. \r\n");
      out.write("    Without his worship no holy work is considered to be complete.</p><br/>\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("  <td>\r\n");
      out.write("   <p style=\"font-family: cursive;font-size: x-large;font-weight: bold;color: Orange\">2. Karni Mata Temple</p><br/>\r\n");
      out.write("   <img src=\"/vision/user/images/temples/Karni-Mata-Medium.jpg\" />\r\n");
      out.write("   <p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\">Karni Mata Temple is situated at Machhla Hills and surrounded by the bliss of the nature. \r\n");
      out.write("   Being situated at height, people can enjoy the panoramic view of Lake Pichhola, Dudh Talai and Sajjangarh. \r\n");
      out.write("   The sunset could be enjoyed in the evening from the sunset point built beside the temple. The temple could be reached through the rope way that starts from Dudh Talai or through stairs that starts from Deendayal Upadhyay Park. \r\n");
      out.write("   Maharana Karan Singh made residence at Machhla Magra between 1620 and 1628. During this time the temple was built. \r\n");
      out.write("   For a long time it remained as a deserted place and in 1997 Manshapurna Karni Mata Development Committee renovated it.</p><br/>\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("  <td>\r\n");
      out.write("   <p style=\"font-family: cursive;font-size: x-large;font-weight: bold;color: Orange\">3. Ekling Ji Temple</p><br/>\r\n");
      out.write("   <img src=\"/vision/user/images/temples/eklingji-temple-640x474.jpg\" />\r\n");
      out.write("   <p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\">Ekling Ji temple is situated 22 kilometers far from Udaipur. \r\n");
      out.write("   It is said that the forefathers of Bappa Rawal ruled the Mewar dynasty. They had enmity with the Mauryas.\r\n");
      out.write("   The Mauryas wanted to kill their family. His mother escaped and came to a place known as Kailashpuri.\r\n");
      out.write("    Bappa started grazing herd of cows. One day he noticed that a cow entered into the dense bushes and at a lonely place and started shredding milk. \r\n");
      out.write("   The place was later recognized as shivalingam and after that Ekling ji temple was built by Bappa Rawal.</p><br/>\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("  <td>\r\n");
      out.write("   <p style=\"font-family: cursive;font-size: x-large;font-weight: bold;color: Orange\">4. Jagdish Temple </p><br/>\r\n");
      out.write("   <img src=\"/vision/user/images/temples/Jagdish-Mandir-Medium.jpg\" />\r\n");
      out.write("   <p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\">Jagdish Temple was built by Maharana Jagat Singh of Udaipur. \r\n");
      out.write("   Maharana Jagat Singh had deep devotion in Lord Jaganath Puri of Orissa. He used to visit Jagan Nath temple in every annual rath yatra.\r\n");
      out.write("    At one occasion he could not reached at the rath yatra on time and he had to halt in the midst of his journey.\r\n");
      out.write("    Maharana got disappointed a lot that he could not attend the rath yatra.\r\n");
      out.write("    When re reached there he had a dream in which the Lord told him that there is no need to travel such long distance and he could made a temple in his city itself.\r\n");
      out.write("    After returning Udaipur he started the construction of the temple.</p><br/>\r\n");
      out.write("   </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("  <td>\r\n");
      out.write("   <p style=\"font-family: cursive;font-size: x-large;font-weight: bold;color: Orange\">5. Neemach Mata </p><br/>\r\n");
      out.write("   <img src=\"/vision/user/images/temples/Neemach-Mata-Medium.jpg\" />\r\n");
      out.write("   <p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\">Neemach Mata is a famous temple in Udaipur and it is situated at a small hill top near Fateh Sagar Lake. According to the residents here this temple is also considered as Vaishno Devi of Udaipur.\r\n");
      out.write("    The name Neemach Mata came due to its origin, which is under a Neem tree. People here believe that those who come here regularly and offer their worship never get any skin ailments due to the strong spiritual spirit of the neem tree. \r\n");
      out.write("   Several pilgrims and tourists visit the Neemach Mata temple every year.</p><br/>\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("  <td>\r\n");
      out.write("   <p style=\"font-family: cursive;font-size: x-large;font-weight: bold;color: Orange\">6. Shrinath Ji Temple </p><br/>\r\n");
      out.write("   <img src=\"/vision/user/images/temples/Shriji.jpg\" />\r\n");
      out.write("   <p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\">Shrinath Ji temple is situated at Nathdwara, which is around 50 kilometers from Udaipur city and it is also termed as the gateway to lord Shrinath Ji.\r\n");
      out.write("    The temple was built in 17th century and owes a great story behind it. It is said that an idol of Lord Krishna was transferred to a distant and safer place from Vrindavan. There were chances of its destruction of the idol by the Mughal Emperor Aurangzeb. When the idol reached this placed the bull cart stuck in deep mud and could not moved further.\r\n");
      out.write("    The priest accompanying the idol thought it as the right place and therefore Shrinath Ji temple was built in Nathdwara.</p><br/>\r\n");
      out.write("   </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("  <td>\r\n");
      out.write("   <p style=\"font-family: cursive;font-size: x-large;font-weight: bold;color: Orange\">7. Ambamata Temple </p><br/>\r\n");
      out.write("   <img src=\"/vision/user/images/temples/Amba-Mata-Ji-Medium.jpg\" />\r\n");
      out.write("   <p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\">The Ambamata Temple deserves the fame as it is one of the main temple of Udaipur. \r\n");
      out.write("    The temple too has a fascinating story behind its construction. It is been said that the erstwhile Maharana of Udaipur Maharana Raj Singh had severe eye problem that did not recovered after treatment.\r\n");
      out.write("    Someone suggested Maharana Raj Singh to have darshan of Amba Mata in Gujarat.\r\n");
      out.write("    At the night before the departure for his journey he had a dream of Goddesses that told him to construct the temple in Udaipur.\r\n");
      out.write("    Next day Maharana visited the place where he found the statue of Ambamata and started the construction of the temple and his ailment also recovered very soon.\r\n");
      out.write("    The spirituality of the temple is so strong that from the poorest to richest person in the world including celebrities & stars visit Shrinath Ji temple for darshans and manoraths.</p><br/>\r\n");
      out.write("   </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("  <td>\r\n");
      out.write("   <p style=\"font-family: cursive;font-size: x-large;font-weight: bold;color: Orange\">8. Sagasji Bavji Temple</p><br/>\r\n");
      out.write("   <img src=\"/vision/user/images/temples/Sagas-Ji-Bavji-Medium.jpg\" />\r\n");
      out.write("   <p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\">Sagasji Bavji temple is situated at Sarvaritu Vilas. \r\n");
      out.write("    Sagasji Bavji is worshiped as a symbol of bravery as people say that he never lost a war in his life. Sagasji was son of Maharaj Raj Singh. \r\n");
      out.write("    When Sagasji lost his life his wife Maharani Kunwariprada became a sati. Every year Sagasji's birthday is celebrated with full glory and fervor.\r\n");
      out.write("    Thousands of devotees wait in long queues to have a glimpse of Sagasji Maharaj. There is a large idol of Ganesh Ji that catches eye of devotees visiting the temple.\r\n");
      out.write("    On his birthday the temple remains open for 24 hours for few days. \r\n");
      out.write("    The occasion is celebrated with night jagrans and the crowd enjoys with full enthusiasm and vigor.</p><br/>\r\n");
      out.write("   </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("  <td>\r\n");
      out.write("   <p style=\"font-family: cursive;font-size: x-large;font-weight: bold;color: Orange\">9. Mahalaxmi Temple </p><br/>\r\n");
      out.write("   <img src=\"/vision/user/images/temples/Mahalakshmi-Temple-Medium.jpg\" />\r\n");
      out.write("   <p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\">The Mahalaxmi Temple is situated at Bhattiyani Chohatta and it was named after Bhati Rani who developed this area. \r\n");
      out.write("    It is said that the temple was built by Maharana Shambhu Singh who fought a battle and brought idols of Mahalaxmi, Rishabhdev and Sundar Vinayak. Mahalaxmi is considered Goddess of wealth and prosperity and worshipped by everyone.\r\n");
      out.write("    The birthday of Mahalaxmi is celebrated every year with fervor and passion. Devotees visits temple and wait in long queues to offer their prayers and Prasad. On the day of Deepawali the temple opens at 5.30 am with the Mangla Aarti. \r\n");
      out.write("    His highness Shri Arvind Singh Mewar visits the temple every Diwali to offer prayers on the occasion of the holy festival of lights.</p><br/>\r\n");
      out.write("   </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("  <td>\r\n");
      out.write("   <p style=\"font-family: cursive;font-size: x-large;font-weight: bold;color: Orange\">10. Mahakaleshwar Temple </p><br/>\r\n");
      out.write("   <img src=\"/vision/user/images/temples/Mahakaleshwara-Temple.jpg\" />\r\n");
      out.write("   <p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\">The marvelous Mahakaleshwar Temple is situated at the bank of Fatehsagar Lake opposite Panna Vilas surrounded by the lush green Aravali Hills. \r\n");
      out.write("    The temple is spread around 3.5 acres of land and great saints like Guru Gorakhnath, the dignified devotee of Lord Shiva, has worshipped here. The devotees have strong faith in Lord Shiva and every day huge number of devotees visits temple to have a glimpse of Mahakaleshwar.\r\n");
      out.write("    The temple opens at 5.30 am with the first prayer and the last prayer takes place at 10.30 pm and the prayers are attended by hundreds of devotees.\r\n");
      out.write("    On special occasions the Rudrabhishek is also performed here by the temple priests.<br/><br/>\r\n");
      out.write("    <a href='#top' style=\"color: Orange\">Back To Top</a></p>\r\n");
      out.write("   </td>\r\n");
      out.write("  </tr>\r\n");
      out.write(" </table>\r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
