/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2014-08-16 06:17:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user.jsp_0020files.museums;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class citypalace_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/user/jsp files/checksession.jsp", Long.valueOf(1407909381372L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");


String usernm = (String) session.getAttribute("username");
if(usernm==null)
	response.sendRedirect("/vision/user/jsp files/index/login_signup.jsp");

      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<script src=\"/vision/user/js files/scroll.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("var image1=new Image()\r\n");
      out.write("image1.src=\"/vision/user/images/citypalace/1280px-Room_of_mirrors,_City_Palace,_Udaipur-qpr.jpg\"\r\n");
      out.write("var image2=new Image()\r\n");
      out.write("image2.src=\"/vision/user/images/citypalace/1280px-Evening_view,_City_Palace,_Udaipur-qpr.jpg\"\r\n");
      out.write("var image3=new Image()\r\n");
      out.write("image3.src=\"/vision/user/images/citypalace/City-Palace-Udaipur-3-qpr.jpg\"\r\n");
      out.write("var image4=new Image()\r\n");
      out.write("image4.src=\"/vision/user/images/citypalace/City-Palace-of-Udaipur-On-Lake-Pichola-India-1600x1200-qpr.jpg\"\r\n");
      out.write("var image5=new Image()\r\n");
      out.write("image5.src=\"/vision/user/images/citypalace/4853914600_b96d3d7396_b-qpr.jpg\"\r\n");
      out.write("var image6=new Image()\r\n");
      out.write("image6.src=\"/vision/user/images/citypalace/1280px-Balconies_with_ceramic_tiles,_City_Palace,_Udaipur-qpr.jpg\"\r\n");
      out.write("var image7=new Image()\r\n");
      out.write("image7.src=\"/vision/user/images/citypalace/1280px-City_Palace_(Udaipur)_07-qpr.jpg\"\r\n");
      out.write("var image8=new Image()\r\n");
      out.write("image8.src=\"/vision/user/images/citypalace/7406424-qpr.jpg\"\r\n");
      out.write("var image9=new Image()\r\n");
      out.write("image9.src=\"/vision/user/images/citypalace/75770112-qpr.jpg\"\r\n");
      out.write("var image10=new Image()\r\n");
      out.write("image10.src=\"/vision/user/images/citypalace/4853099127_5356c76f44_b-qpr.jpg\"\r\n");
      out.write("var image11=new Image()\r\n");
      out.write("image11.src=\"/vision/user/images/citypalace/4853113047_5cce58d4e8_b-qpr.jpg\"\r\n");
      out.write("var image12=new Image()\r\n");
      out.write("image12.src=\"/vision/user/images/citypalace/4853124643_c12e5f2f92_b-qpr.jpg\"\r\n");
      out.write("var image13=new Image()\r\n");
      out.write("image13.src=\"/vision/user/images/citypalace/4853706970_bd83b6679b_b-qpr.jpg\"\r\n");
      out.write("var image14=new Image()\r\n");
      out.write("image14.src=\"/vision/user/images/citypalace/inside-the-city-palace--udaipur-qpr.jpg\"\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("/* hover menu*/\r\n");
      out.write("#indiv tr td a\r\n");
      out.write("{\r\n");
      out.write("    float: left;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 160px;\r\n");
      out.write("\theight: 45px;\r\n");
      out.write("\tpadding: 20px 0px 0 0px;\r\n");
      out.write("\tmargin: 0px 10px 0px 10px ;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor:Black;\t\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#indiv tr td a:hover,#indiv tr td .current\r\n");
      out.write("{\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  background: Black ;\r\n");
      out.write("  color: Orange; \r\n");
      out.write("}\t\r\n");
      out.write("\r\n");
      out.write("#indiv tr td ul li ul li a:hover\r\n");
      out.write("{\r\n");
      out.write("  background:none;\r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write("  color: White; \r\n");
      out.write("}\r\n");
      out.write("/* drop down menu*/\r\n");
      out.write("/*body {\r\n");
      out.write("  font-family: 'Lucida Grande', 'Helvetica Neue', Helvetica, Arial, sans-serif;\r\n");
      out.write("  padding: 20px 50px 150px;\r\n");
      out.write("  font-size: 13px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  background: #E3CAA1;\r\n");
      out.write("}*/\r\n");
      out.write("\r\n");
      out.write("#dropdown ul {\r\n");
      out.write("  text-align: left;\r\n");
      out.write("  display: inline;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 45px 10px 17px 5px;\r\n");
      out.write("  list-style: none;\r\n");
      out.write("  /*-webkit-box-shadow: 0 0 5px rgba(0, 0, 0, 0.15);\r\n");
      out.write("  -moz-box-shadow: 0 0 5px rgba(0, 0, 0, 0.15);\r\n");
      out.write("  box-shadow: 0 0 5px rgba(0, 0, 0, 0.15);*/\r\n");
      out.write("}\r\n");
      out.write("#dropdown ul li {\r\n");
      out.write("  font: bold 16px/16px sans-serif;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  margin-right: 5px;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  padding: 10px 15px;\r\n");
      out.write("  background: rgba(213, 35, 35, 0.67);\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  -webkit-transition: all 0.2s;\r\n");
      out.write("  -moz-transition: all 0.2s;\r\n");
      out.write("  -ms-transition: all 0.2s;\r\n");
      out.write("  -o-transition: all 0.2s;\r\n");
      out.write("  transition: all 0.2s;\r\n");
      out.write("}\r\n");
      out.write("#dropdown ul li:hover {\r\n");
      out.write("  background: rgba(213, 35, 35, 0.67);\r\n");
      out.write("  color: #fff;\r\n");
      out.write("}\r\n");
      out.write("#dropdown ul li ul {\r\n");
      out.write("  padding: 0px;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 52px;\r\n");
      out.write("  left: 0px;\r\n");
      out.write("  width: 130px;\r\n");
      out.write("  /*-webkit-box-shadow: none;\r\n");
      out.write("  -moz-box-shadow: none;\r\n");
      out.write("  box-shadow: none;*/\r\n");
      out.write("  display: none;\r\n");
      out.write("  opacity: 0;\r\n");
      out.write("  visibility: hidden;\r\n");
      out.write("  -webkit-transiton: opacity 0.2s;\r\n");
      out.write("  -moz-transition: opacity 0.2s;\r\n");
      out.write("  -ms-transition: opacity 0.2s;\r\n");
      out.write("  -o-transition: opacity 0.2s;\r\n");
      out.write("  -transition: opacity 0.2s;\r\n");
      out.write("}\r\n");
      out.write("#dropdown ul li ul li { \r\n");
      out.write("  background: rgba(199, 89, 38, 0.67);\r\n");
      out.write("  display: block; \r\n");
      out.write("  color: #fff;\r\n");
      out.write("  //text-shadow: 0 -1px 0 #000;\r\n");
      out.write("}\r\n");
      out.write("#dropdown ul li ul li:hover \r\n");
      out.write("{ background: rgba(199, 89, 38, 0.67);display: none;\r\n");
      out.write("}\r\n");
      out.write("#dropdown ul li:hover ul {\r\n");
      out.write("  display: block;\r\n");
      out.write("  opacity: 1;\r\n");
      out.write("  visibility: visible;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background:url(/vision/user/images/background/parquet_flooring-1920x1200.jpg); background-size: cover; \">\r\n");
      out.write("<table  align=\"center\" width=\"60%\">\r\n");
      out.write(" <tr height=\"40\">\r\n");
      out.write("  <td>\r\n");
      out.write("  <a name=\"top\"></a>\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr height='50' >\r\n");
      out.write(" <td>\r\n");
      out.write("   <table  id='indiv' align=\"center\"><!--table 2 inside table 1-->\r\n");
      out.write("     <tr>\r\n");
      out.write("\t  <td><a href='/vision/user/jsp files/afterlogin/afterlogin_index.jsp' target='_parent'>HOME</a></td>\r\n");
      out.write("      <td><a href='/vision/user/jsp files/about_us.jsp' target='_parent'>ABOUT US</a></td>\r\n");
      out.write("      <td><a href='/vision/user/jsp files/contact_us.jsp' target='_parent'>CONTACT US</a></td>\r\n");
      out.write("      <td><a href='/vision/user/jsp files/afterlogin/afterlogin_information.jsp' target='_parent'>INFORMATION RESOURCE</a></td>\r\n");
      out.write("      <td><a href='/vision/user/jsp files/afterlogin/feedback.jsp' target='_parent'>FEEDBACK</a></td>\r\n");
      out.write("      <td><a href='/vision/user/jsp files/afterlogin/afterlogin_features.jsp' target='_top'class='current'>FEATURES</a></td>\r\n");
      out.write("      <td><img src='/vision/user/images/loginform/user1.png'></img></td>\r\n");
      out.write("\t  <td id=dropdown>\r\n");
      out.write("\t   <ul >\r\n");
      out.write("\t    <li style=\"width: 83px;height: 33px\">\r\n");
      out.write("        Hi, ");
String usrname=(String) session.getAttribute("username");
      out.print(usrname );
      out.write("\r\n");
      out.write("\t\t <ul>\r\n");
      out.write("          <li style=\"float: left;display: inherit; \" ><a href='/vision/LogoutServlet' style=\"font-size: inherit;text-align: left;  width: 63px; height: 8px; \">Log Out</a></li>\r\n");
      out.write("     \t  <li style=\"float: left;display: inherit; \"><a href='/vision/UpdateServlet' style=\"font-size: inherit;text-align: left; width: 107px; height: 17px \">Update profile</a></li>\r\n");
      out.write("\t\t </ul>\t\t\t\t\t\t\t\t\r\n");
      out.write(" \t\t</li>\t\t\t    \r\n");
      out.write("       </ul>         \r\n");
      out.write("      </td>                  \r\n");
      out.write("    \t\t\t\t  \r\n");
      out.write("\t </tr>\r\n");
      out.write("\t\t\t   \r\n");
      out.write("    </table><!--end of table 2-->                  \r\n");
      out.write("   </td>       \t            \r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr height='30'>\r\n");
      out.write("   <td>\r\n");
      out.write("   </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("   <td>\r\n");
      out.write("   <p style=\"font-family: cursive;font-size: x-large;font-weight: bold;color: Orange;text-align: center;\">CITY PALACE MUSEUM</p>\r\n");
      out.write("   </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr height='20'>\r\n");
      out.write("   <td>\r\n");
      out.write("   </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("   <td align=\"center\">\r\n");
      out.write("    <img src=\"/vision/user/images/citypalace/4853099127_5356c76f44_b-qpr.jpg\".jpg\" name=\"slide\" width=\"1024px\" height=\"500px\"  />\r\n");
      out.write("    <script>\r\n");
      out.write("\t <!--\r\n");
      out.write("\t //variable that will increment through the images\r\n");
      out.write("\t var step=1;\r\n");
      out.write("\t function slideit(){\r\n");
      out.write("\t //if browser does not support the image object, exit.\r\n");
      out.write("\t if (!document.images)\r\n");
      out.write("\t return\r\n");
      out.write("\t document.images.slide.src=eval(\"image\"+step+\".src\");   \r\n");
      out.write(" \t if (step<14)\r\n");
      out.write("\t step++;\r\n");
      out.write("\t else\r\n");
      out.write("\t step=1;\r\n");
      out.write("\t //call function \"slideit()\" every 2.5 seconds\r\n");
      out.write("\t setTimeout(\"slideit()\",4000);\r\n");
      out.write("\t }\r\n");
      out.write("\t slideit();\r\n");
      out.write("\t //-->\r\n");
      out.write("\t</script>\r\n");
      out.write("   </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr height='60'>\r\n");
      out.write("  <tr>\r\n");
      out.write("   <td>\r\n");
      out.write("   <p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\">\r\n");
      out.write("   More than four centuries ago, in A.D. 1559, Rana Udai Singh II the father of Rana Pratap, laid the Foundation of the City Palace after the birth of his grandson Amar Singh I and on the advice of a Hermit Goswami Prem Giriji Maharaj,\r\n");
      out.write("   who had a small hut on this hill. The enormous complex of the old palace standing on a low ridge called Rana Magri (Rana's Hill) overlooking lake Pichola on the west is a tribute to the constructive genius and architectural taste of the Maharana's of Mewar,\r\n");
      out.write("   ranging from Rana Udai Singh II to the present 76th Custodian of House of Mewar, Shriji Arvind Singh Mewar.</p>\r\n");
      out.write("   \r\n");
      out.write("  <p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\"> It has been so planned and integrated with the original building that the entire structure assumes a shape of one edifice from the exterior, with canopies, towers, domes, cupolas, bastions, beautifully carved balconies and ornamental turrets.\r\n");
      out.write("   The City Palace built by Rana Udai Singh II has been added to and extended by the successive generations of Maharanas, notably by Rana Karan Singh, and Rana Sangram Singh II. Maharana Sajjan Singh and Maharana Fateh Singh further expanded the palace in the 19th century.\r\n");
      out.write("   The building is a unique depiction of the architectural and artistic evolution of Mewar through centuries.</p>\r\n");
      out.write("   \r\n");
      out.write("   <p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\">The City Palace has always been a self-sufficient developing centre within itself and shall continue to grow into an ideal prototype of a living palace complex.\r\n");
      out.write("   The City Palace Museum, Udaipur was set up in 1969 by Maharana Bhagwat Singh ji to safeguard and preserve the cultural heritage and the time honoured traditions of the people of Mewar.\r\n");
      out.write("   The City Palace was built by Maharana Udai Mirza Singh as the capital of the Sisodia Rajput clan in 1559, after he moved from Chittor.Considered the largest of its kind in Rajasthan, the palatial building displays a fusion of the Rajasthani and Mughal architectural styles.</p>\r\n");
      out.write("   \r\n");
      out.write("   <p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\">Built on a hilltop, the palace provides an aerial view of the city and its surrounding.With the establishment of Udaipur City by Maharana Udai Singh in 1559, the palace was built concurrently. Set at an average elevation of 598 metres, the palace has various towers, domes and arches,\r\n");
      out.write("   which add to the flavour of this heritage site.Courtyards, pavilions, terraces, corridors, rooms and hanging gardens make up the entire palace. 'Pols' is used to refer to the gates of the palace.Eight marble arches or toranas, where kings used to weigh themselves with gold and silver, \r\n");
      out.write("   are located between these two gates. Near Tripolia lies an arena where elephant fights were staged.The interior of the palace is adorned with unique paintings, antique furniture and exquisite glass, mirror and ornamental tiles work.Figures of crystal and porcelain embellish the Manak Mahal (Ruby Palace). \r\n");
      out.write("   A collection of miniature paintings depicting the real life stories of Radha-Krishna adorn the Bhim Vilas.An album of miniature paintings portraying royal processions, festivals and games of the Maharanas is the highlight of the 'Krishna Vilas'. While Sheesh Mahal (Palace of Mirrors) is known for it mirror work, \r\n");
      out.write("   Moti Mahal (Pearl Palace) is celebrated for its lavish decor. The biggest temple of the city, Jagdish Temple is also located within the palace complex.\r\n");
      out.write("   </p><br/>\r\n");
      out.write("   <p><a href='http://www.hrhhotels.com/regal-visits/city-palace-museum.aspx' target='_parent' style=\"color: Orange\">For More Information</a>\r\n");
      out.write("   </p>\r\n");
      out.write("   <a href='#top' style=\"color: Orange\">Back To Top</a>\r\n");
      out.write("   </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  </table>\r\n");
      out.write("  </body>\r\n");
      out.write("  </html>\r\n");
      out.write("  \r\n");
      out.write("  ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
