/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2014-08-16 06:17:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user.jsp_0020files.museums;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class museums_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/user/jsp files/checksession.jsp", Long.valueOf(1407909381372L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");


String usernm = (String) session.getAttribute("username");
if(usernm==null)
	response.sendRedirect("/vision/user/jsp files/index/login_signup.jsp");

      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<script src=\"/vision/user/js files/scroll.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("/* hover menu*/\r\n");
      out.write("#indiv tr td a\r\n");
      out.write("{\r\n");
      out.write("    float: left;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 160px;\r\n");
      out.write("\theight: 45px;\r\n");
      out.write("\tpadding: 20px 0px 0 0px;\r\n");
      out.write("\tmargin: 0px 10px 0px 10px ;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor:Black;\t\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#indiv tr td a:hover,#indiv tr td .current\r\n");
      out.write("{\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  background: Black ;\r\n");
      out.write("  color: Orange; \r\n");
      out.write("}\t\r\n");
      out.write("\r\n");
      out.write("#indiv tr td ul li ul li a:hover\r\n");
      out.write("{\r\n");
      out.write("  background:none;\r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write("  color: White; \r\n");
      out.write("}\r\n");
      out.write("/* drop down menu*/\r\n");
      out.write("/*body {\r\n");
      out.write("  font-family: 'Lucida Grande', 'Helvetica Neue', Helvetica, Arial, sans-serif;\r\n");
      out.write("  padding: 20px 50px 150px;\r\n");
      out.write("  font-size: 13px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  background: #E3CAA1;\r\n");
      out.write("}*/\r\n");
      out.write("\r\n");
      out.write("#dropdown ul {\r\n");
      out.write("  text-align: left;\r\n");
      out.write("  display: inline;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 45px 10px 17px 5px;\r\n");
      out.write("  list-style: none;\r\n");
      out.write("  /*-webkit-box-shadow: 0 0 5px rgba(0, 0, 0, 0.15);\r\n");
      out.write("  -moz-box-shadow: 0 0 5px rgba(0, 0, 0, 0.15);\r\n");
      out.write("  box-shadow: 0 0 5px rgba(0, 0, 0, 0.15);*/\r\n");
      out.write("}\r\n");
      out.write("#dropdown ul li {\r\n");
      out.write("  font: bold 16px/16px sans-serif;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  margin-right: 5px;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  padding: 10px 15px;\r\n");
      out.write("  background: rgba(213, 35, 35, 0.67);\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  -webkit-transition: all 0.2s;\r\n");
      out.write("  -moz-transition: all 0.2s;\r\n");
      out.write("  -ms-transition: all 0.2s;\r\n");
      out.write("  -o-transition: all 0.2s;\r\n");
      out.write("  transition: all 0.2s;\r\n");
      out.write("}\r\n");
      out.write("#dropdown ul li:hover {\r\n");
      out.write("  background: rgba(213, 35, 35, 0.67);\r\n");
      out.write("  color: #fff;\r\n");
      out.write("}\r\n");
      out.write("#dropdown ul li ul {\r\n");
      out.write("  padding: 0px;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 52px;\r\n");
      out.write("  left: 0px;\r\n");
      out.write("  width: 130px;\r\n");
      out.write("  /*-webkit-box-shadow: none;\r\n");
      out.write("  -moz-box-shadow: none;\r\n");
      out.write("  box-shadow: none;*/\r\n");
      out.write("  display: none;\r\n");
      out.write("  opacity: 0;\r\n");
      out.write("  visibility: hidden;\r\n");
      out.write("  -webkit-transiton: opacity 0.2s;\r\n");
      out.write("  -moz-transition: opacity 0.2s;\r\n");
      out.write("  -ms-transition: opacity 0.2s;\r\n");
      out.write("  -o-transition: opacity 0.2s;\r\n");
      out.write("  -transition: opacity 0.2s;\r\n");
      out.write("}\r\n");
      out.write("#dropdown ul li ul li { \r\n");
      out.write("  background: rgba(199, 89, 38, 0.67);\r\n");
      out.write("  display: block; \r\n");
      out.write("  color: #fff;\r\n");
      out.write("  //text-shadow: 0 -1px 0 #000;\r\n");
      out.write("}\r\n");
      out.write("#dropdown ul li ul li:hover \r\n");
      out.write("{ background: rgba(199, 89, 38, 0.67);display: none;\r\n");
      out.write("}\r\n");
      out.write("#dropdown ul li:hover ul {\r\n");
      out.write("  display: block;\r\n");
      out.write("  opacity: 1;\r\n");
      out.write("  visibility: visible;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background:url(/vision/user/images/background/parquet_flooring-1920x1200.jpg); background-size: cover; \">\r\n");
      out.write("<table  align=\"center\" width=\"60%\">\r\n");
      out.write(" <tr height=\"40\">\r\n");
      out.write("  <td>\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr height='50' >\r\n");
      out.write(" <td>\r\n");
      out.write("   <table  id='indiv' align=\"center\"><!--table 2 inside table 1-->\r\n");
      out.write("     <tr>\r\n");
      out.write("\t  <td><a href='/vision/user/jsp files/afterlogin/afterlogin_index.jsp' target='_parent'>HOME</a></td>\r\n");
      out.write("      <td><a href='/vision/user/jsp files/about_us.jsp' target='_parent'>ABOUT US</a></td>\r\n");
      out.write("      <td><a href='/vision/user/jsp files/contact_us.jsp' target='_parent'>CONTACT US</a></td>\r\n");
      out.write("      <td><a href='/vision/user/jsp files/afterlogin/afterlogin_information.jsp' target='_parent'>INFORMATION RESOURCE</a></td>\r\n");
      out.write("      <td><a href='/vision/user/jsp files/afterlogin/feedback.jsp' target='_parent'>FEEDBACK</a></td>\r\n");
      out.write("      <td><a href='/vision/user/jsp files/afterlogin/afterlogin_features.jsp' target='_top'class='current'>FEATURES</a></td>\r\n");
      out.write("      <td><img src='/vision/user/images/loginform/user1.png'></img></td>\r\n");
      out.write("\t  <td id=dropdown>\r\n");
      out.write("\t   <ul >\r\n");
      out.write("\t    <li style=\"width: 83px;height: 33px\">\r\n");
      out.write("        Hi, ");
String usrname=(String) session.getAttribute("username");
      out.print(usrname );
      out.write("\r\n");
      out.write("\t\t <ul>\r\n");
      out.write("          <li style=\"float: left;display: inherit; \" ><a href='/vision/LogoutServlet' style=\"font-size: inherit;text-align: left;  width: 63px; height: 8px; \">Log Out</a></li>\r\n");
      out.write("     \t  <li style=\"float: left;display: inherit; \"><a href='/vision/UpdateServlet' style=\"font-size: inherit;text-align: left; width: 107px; height: 17px \">Update profile</a></li>\r\n");
      out.write("\t\t </ul>\t\t\t\t\t\t\t\t\r\n");
      out.write(" \t\t</li>\t\t\t    \r\n");
      out.write("       </ul>         \r\n");
      out.write("      </td>                  \r\n");
      out.write("    \t\t\t\t  \r\n");
      out.write("\t </tr>\r\n");
      out.write("\t\t\t   \r\n");
      out.write("    </table><!--end of table 2-->                  \r\n");
      out.write("   </td>       \t            \r\n");
      out.write("  </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("  <td>\r\n");
      out.write("  <a name=\"top\"></a>\r\n");
      out.write("  <br/>\r\n");
      out.write("   <p style=\"font-family: cursive;font-size: x-large;font-weight: bold;color: Orange\">MUSEUMS IN UDAIPUR</p>\r\n");
      out.write("   <p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\">\r\n");
      out.write("   Udaipur is a majestic city that presents artifacts of the bygone age by the means of museums. These museums peep into the ancient times of the imperial city.\r\n");
      out.write("   If you have planned to come to the city of Udaipur, then take out some time to visit the art museums of Udaipur.\r\n");
      out.write("   These museums are made to preserve the priceless objects of the noble kings. Various museums of Udaipur offer a glimpse of the items that used to be the part of the regal lifestyle.\r\n");
      out.write("   Udaipur Government is making constant efforts to preserve the artifacts of the previous age. If you are keen to know about the glorious past, these museums would be of great interest for you. \r\n");
      out.write("   </p><br/>\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" \r\n");
      out.write(" <tr>\r\n");
      out.write("  <td>\r\n");
      out.write("   <p style=\"font-family: cursive;font-size: x-large;font-weight: bold;color: Orange\">CITY PALACE MUSEUM</p>\r\n");
      out.write("   <img src=\"/vision/user/images/museums/city_palace_Udaipur1-qpr.jpg\" />\r\n");
      out.write("   <p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\">\r\n");
      out.write("   More than four centuries ago, in A.D. 1559, Rana Udai Singh II the father of Rana Pratap, laid the Foundation of the City Palace after the birth of his grandson Amar Singh I and on the advice of a Hermit Goswami Prem Giriji Maharaj,\r\n");
      out.write("   who had a small hut on this hill. The enormous complex of the old palace standing on a low ridge called Rana Magri (Rana's Hill) overlooking lake Pichola on the west is a tribute to the constructive genius and architectural taste of the Maharana's of Mewar,\r\n");
      out.write("   ranging from Rana Udai Singh II to the present 76th Custodian of House of Mewar, Shriji Arvind Singh Mewar.\r\n");
      out.write("   It has been so planned and integrated with the original building that the entire structure assumes a shape of one edifice from the exterior, with canopies, towers, domes, cupolas, bastions, beautifully carved balconies and ornamental turrets.\r\n");
      out.write("   The City Palace built by Rana Udai Singh II has been added to and extended by the successive generations of Maharanas, notably by Rana Karan Singh, and Rana Sangram Singh II. Maharana Sajjan Singh and Maharana Fateh Singh further expanded the palace in the 19th century.\r\n");
      out.write("   \r\n");
      out.write("   <a href='/vision/user/jsp files/museums/citypalace.jsp' target='_parent' style=\"color: Orange\">Read More</a>\r\n");
      out.write("   </p><br/>\r\n");
      out.write("   </td>\r\n");
      out.write(" </tr>\r\n");
      out.write("   \r\n");
      out.write(" <tr>\r\n");
      out.write("  <td>\r\n");
      out.write("   <p style=\"font-family: cursive;font-size: x-large;font-weight: bold;color: Orange\">THE VINTAGE AND CLASSIC CAR COLLECTION</p>\r\n");
      out.write("   <img src=\"/vision/user/images/museums/vintage-collection-of-classic-cars-museum-udaipur-qpr.jpg\" />\r\n");
      out.write("   <p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\">\r\n");
      out.write("   A unique private collection of vintage cars of the House of Mewar - the world's longest serving dynasty\r\n");
      out.write("   The Vintage & Classic Car Collection is a landmark in the city of Udaipur ever since it was inaugurated in February 2000. \r\n");
      out.write("   The grand limousines and cars showcased in the Collection belong to the House of Mewar and are still in perfect running condition. \r\n");
      out.write("   Visitors are privy to the display of the magnificent Rolls-Royce, 1939 Cadillac open convertibles, rare Mercedes models, 1936 Vauxhall and 1937 Opel models. \r\n");
      out.write("   The Collection has been curated for the benefit of vintage car-lovers from India and all over the world; it is probably the only collection of its kind in India about which the global and indian press has written reams. \r\n");
      out.write("   Awe-struck visitors to the Collection are narrated innumerable stories and anecdotes about the Maharanas of Mewar and their preferred Rolls-Royce or Mercedes customised at their request.\r\n");
      out.write("  <a href='/vision/user/jsp files/museums/vintage.jsp' target='_parent' style=\"color: Orange\" >Read More</a>\r\n");
      out.write("   </p><br/>\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write("   \r\n");
      out.write(" <tr>\r\n");
      out.write("  <td>\r\n");
      out.write("   <p style=\"font-family: cursive;font-size: x-large;font-weight: bold;color: Orange\">AHAR MUSEUM</p>\r\n");
      out.write("   <img src=\"/vision/user/images/museums/13731263-qpr.jpg\" />\r\n");
      out.write("   <p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\">\r\n");
      out.write("   The Ahar Museum, Udaipur is named after the beautiful city Ahar, where this museum is located. Ahar is the capital of Sisodias and is about 3 Kms away from Udaipur, in Rajasthan. \r\n");
      out.write("   There are various types of iron objects and also a wide variety of other objects of art forms in the magnificent Ahar Museum. These objects are around 5000 years old.\r\n");
      out.write("   Earthen Pots are among the rare collection of antiquities in Ahar Museum.\r\n");
      out.write("   The architectural pieces stored in the museum are extremely old, as a matter of fact some of the pieces date back to 1700 BC.\r\n");
      out.write("   One of the major attractions and an eye catcher is a Buddha statue, which is a 10th century figure made out of metal.\r\n");
      out.write("   There are a huge number of cenotaphs in Ahar Museum in Udaipur, India. There are about nineteen cenotaphs of the great Maharanas which are cremated there. \r\n");
      out.write("   Among all the cenotaphs in Ahar Museum, Rajasthan, one of the most striking cenotaphs is that of Maharana Amar Singh, who ruled during the period 1597 to 1620.\r\n");
      out.write("   </p><br/>\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write("   \r\n");
      out.write(" <tr>\r\n");
      out.write("  <td>\r\n");
      out.write("   <p style=\"font-family: cursive;font-size: x-large;font-weight: bold;color: Orange\">SHILPGRAM MUSEUM</p>\r\n");
      out.write("   <img src=\"/vision/user/images/museums/shilpgram-museum4-qpr.jpg\" />\r\n");
      out.write("   <p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\">\r\n");
      out.write("   Literally meaning a \"Craftsmen's Village\" is a living ethnographic museum depicting the enormous diversities in craft, art & culture between various Indian states,\r\n");
      out.write("   but the exquisite terracotta work mainly in dark red and dark brown sand material along with the wooden carvings are the forte of this ethnic village . \r\n");
      out.write("   Shilpgram comprises 26 huts set in 70 acres of natural surroundings at the foot of the Aravali Hills.A colourful craft festival during winter seasons to the whole set up induces viatanity and zeal.\r\n");
      out.write("   Situated 3 kms west of Udaipur near the Havala village is the Centre's Shilpgram - the Rural Arts and Crafts Complex. Spread over an undulating terrain of 130 bighas (70 Acres) of land and surrounded by the Aravallies, \r\n");
      out.write("   the Rural Arts and Crafts Complex is conceived as a living enthnographic museum to depict the lifestyles of the folk and tribal people of the West Zone. Within this complex,\r\n");
      out.write("   huts of the member states are constructed incorporating traditional architectural features of different geographical and ethnic groups residing within the West Zone of India comprising of five Federal States.\r\n");
      out.write("   </p><br/>\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" \r\n");
      out.write(" <tr>\r\n");
      out.write("  <td>\r\n");
      out.write("   <p style=\"font-family: cursive;font-size: x-large;font-weight: bold;color: Orange\">BHARTIYA LOK KALA MANDAL</p>\r\n");
      out.write("   <img src=\"/vision/user/images/museums/lok-kala-mandal-udaipur-qpr.jpg\" />\r\n");
      out.write("   <p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\"> \r\n");
      out.write("   Bhartiya Lok Kala Museum is one of the most famous museums of Udaipur, exhibiting the brilliant collection of folk articles of Rajasthan.\r\n");
      out.write("   This rare compilation varies from typical rural-dresses, ornaments, puppets, masks, dolls, folk musical instruments, folk deities and paintings.\r\n");
      out.write("   The museum is comfortably located in the building of Bhartiya Lok Kala Mandal near Chetak Circle in Udaipur city.\r\n");
      out.write("   Mewar region of Rajasthan is known for its rich art and culture. Actually, the local handicrafts and things of art of this region have always been cherished all over the world.\r\n");
      out.write("   With the intention to maintain this rich tradition, Bhartiya Lok Kala Mandal took the initiative, to start an institution, to encourage the local arts and crafts of Mewar.\r\n");
      out.write("   Bhartiya Lok Kala Museum is a part of their program that displays the best art and craft of Mewar.\r\n");
      out.write("   The museum portrays the remarkable collection of over past 44 years, gathered by the Bhartiya Lok Kala Mandal. To provide a summarized idea of the folk heritage of India, traditional attires, ornaments, miniature paintings and many other art objects are displayed here. Bhartiya Lok Kala Museum of Udaipur definitely requires a visit to closely observe the artistic and culturally rich region of Rajasthan. \r\n");
      out.write("   </p><br/>\r\n");
      out.write("   <a href='#top' style=\"color: Orange\">Back To Top</a>\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr> \r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("  ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
