/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2014-08-08 13:43:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminhotelentry_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/admin/adminchecksession.jsp", Long.valueOf(1406573955451L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");


String usernm = (String) session.getAttribute("username");
if(usernm==null)
	response.sendRedirect("/vision/admin/adminlogin.jsp");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type='text/Javascript' src=\"/vision/admin/admin_hotelentry.js\"></script><!-- different javascript file for validation for username and password of admin only-->\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".height\r\n");
      out.write(" {\r\n");
      out.write("  height:auto;\r\n");
      out.write(" }\r\n");
      out.write("#hotelnameError\r\n");
      out.write(" {\r\n");
      out.write("  font-size:12px;color:#FF0000;font-weight: bold;\r\n");
      out.write(" } \r\n");
      out.write("#hoteldescriptionError\r\n");
      out.write(" {\r\n");
      out.write("  font-size:12px;color:#FF0000;font-weight: bold;\r\n");
      out.write(" }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form id=\"hotelentry\" name=\"hotelentry\"  method=\"post\" enctype=\"multipart/form-data\" action=\"/vision/admin/insertimage.jsp\">\r\n");
      out.write("<table  align='center'>\r\n");
      out.write(" \r\n");
      out.write(" <tr height='100'>\r\n");
      out.write("  <td>\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" \r\n");
      out.write(" <tr height='50'>\r\n");
      out.write("  <td align=\"center\" style=\"font-family: monospace;font-size: large;font-weight: bold;\">ADMIN HOTEL ENTRY</td> \r\n");
      out.write(" </tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <tr>\r\n");
      out.write("  <td>HOTEL NAME:</td>\r\n");
      out.write("  <td><input type=\"text\" name='hotelname' id=\"hotelname\" maxlength='50' placeholder=\"Hotel Name\" style=\"width:280px;height:15px\" /></td>\r\n");
      out.write("  <td align=\"center\" width=\"150\"class='height' id=\"hotelnameError\">&nbsp; </td>\r\n");
      out.write(" </tr> \r\n");
      out.write("  \r\n");
      out.write(" <tr> \r\n");
      out.write("  <td>HOTEL DESCRIPTION:</td>\r\n");
      out.write("  <td><textarea name=\"hoteldescription\" id=\"hoteldescription\" rows=\"10\" cols=\"100\"  ></textarea></td>\r\n");
      out.write("  <td align=\"center\" width=\"150\"class='height' id=\"hoteldescriptionError\">&nbsp; </td>\r\n");
      out.write(" </tr> \r\n");
      out.write("  \r\n");
      out.write(" <tr> \r\n");
      out.write("  <td>VISIT LINKS:</td>\r\n");
      out.write("  <td><input type=\"text\" name='visitlinks' id=\"visitlinks\"  placeholder=\"Visit Link\" style=\"width:480px;height:15px\" /></td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" \r\n");
      out.write(" <tr>\r\n");
      out.write("  <td>CHOOSE HOTEL IMAGE:</td>\r\n");
      out.write("  <td><input type=\"file\" name='ImageFile' id='ImageFile'  /></td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" \r\n");
      out.write(" <tr height='30'>\r\n");
      out.write("  <td>\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" \r\n");
      out.write(" <tr>\r\n");
      out.write("   <td align=\"center\"><input type=\"submit\" name=\"submit\" value=\"Submit\"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type='reset' name='cancel' value='Cancel' id='reset' /></td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" \r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
