/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2014-11-13 09:33:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user.jsp_0020files.index;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/vision/user/css files/slider.css\"  />\r\n");
      out.write("<script src=\"/vision/user/js files/slider.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>Untitled Document</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("#indiv tr td a\r\n");
      out.write("{\r\n");
      out.write("    float: left;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 160px;\r\n");
      out.write("\theight: 45px;\r\n");
      out.write("\tpadding: 20px 0px 0 0px;\r\n");
      out.write("\tmargin: 0px 10px 0px 10px ;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor:Black;\t\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#indiv tr td a:hover,#indiv tr td .current\r\n");
      out.write("{\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  background: Black ;\r\n");
      out.write("  color: Orange; \r\n");
      out.write("}\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"background:url(/vision/user/images/background/parquet_flooring-1920x1200.jpg);background-size: cover \">\r\n");
      out.write("<table align=\"center\" width=\"100%\">\r\n");
      out.write(" <tr height=\"40\">\r\n");
      out.write("  <td>\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr height='50' >\r\n");
      out.write("  <td>\r\n");
      out.write("   <table id='indiv' align=\"center\"><!--table 2 inside table 1-->\r\n");
      out.write("     <tr>\r\n");
      out.write("\t  <td><a href='/vision/user/jsp files/index/index.jsp' target='_top' class='current'>HOME</a></td>\r\n");
      out.write("      <td><a href='/vision/user/jsp files/index/about_us.jsp' target='_top'>ABOUT US</a></td>\r\n");
      out.write("      <td><a href='/vision/user/jsp files/index/contact_us.jsp' target='_top'>CONTACT US</a></td>\r\n");
      out.write("      <td><a href='/vision/user/jsp files/index/information.jsp' target='_top'>INFORMATION RESOURCE</a></td>\r\n");
      out.write("      <td><a href='/vision/user/jsp files/index/features.jsp' target='_top'>FEATURES</a></td>\r\n");
      out.write("      <td><a href='/vision/user/jsp files/index/login_signup.jsp' target='_parent'>LOGIN/Sign Up</a></td>            \r\n");
      out.write("\t </tr>\t\t\t   \r\n");
      out.write("    </table><!--end of table 2-->                  \r\n");
      out.write("   </td>       \t            \r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr height='40'>\r\n");
      out.write("   <td>\r\n");
      out.write("   </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr height='530'>\r\n");
      out.write("   <td>\r\n");
      out.write("   \r\n");
      out.write("   <div id=\"sliderFrame\">\r\n");
      out.write("        <div id=\"slider\">\r\n");
      out.write("            <img src=\"/vision/user/images/slider/DSC02654-qpr.jpg\" />\r\n");
      out.write("            <img src=\"/vision/user/images/slider/DSC01672-qpr.jpg\" />\r\n");
      out.write("            <img src=\"/vision/user/images/slider/DSC02647-qpr.jpg\" />\r\n");
      out.write("            <img src=\"/vision/user/images/slider/DSC00619-qpr.jpg\" />\r\n");
      out.write("            <img src=\"/vision/user/images/slider/DSC00779-qpr.jpg\" />\r\n");
      out.write("            <img src=\"/vision/user/images/slider/DSC00780-qpr.jpg\" />\r\n");
      out.write("\t\t\t<img src=\"/vision/user/images/slider/DSC00792-qpr.jpg\" />\r\n");
      out.write("\t\t\t<img src=\"/vision/user/images/slider/DSC00804-qpr.jpg\" />\r\n");
      out.write("\t\t\t<img src=\"/vision/user/images/slider/DSC00834-qpr.jpg\" />\r\n");
      out.write("\t\t\t<img src=\"/vision/user/images/slider/DSC01215-qpr.jpg\" />\r\n");
      out.write("\t\t\t<img src=\"/vision/user/images/slider/DSC02603-qpr.jpg\" />\r\n");
      out.write("\t\t\t<img src=\"/vision/user/images/slider/DSC_1164-qpr.jpg\" />\r\n");
      out.write("\t\t\t<img src=\"/vision/user/images/slider/DSC02639-qpr.jpg\" />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("   \r\n");
      out.write("   </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  </table><!-- end of table 1-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>           \t      \r\n");
      out.write("\t\t\t  \r\n");
      out.write("            \r\n");
      out.write("  \r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
