/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2014-08-13 05:52:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user.jsp_0020files.index;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class information_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<script src=\"/vision/user/js files/scroll.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(" \r\n");
      out.write("/* hover div*/\r\n");
      out.write("#indiv tr td a\r\n");
      out.write("{\r\n");
      out.write("    float: left;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 160px;\r\n");
      out.write("\theight: 45px;\r\n");
      out.write("\tpadding: 20px 0px 0 0px;\r\n");
      out.write("\tmargin: 0px 10px 0px 10px ;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor:Black;\t\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#indiv tr td a:hover,#indiv tr td .current\r\n");
      out.write("{\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  background: Black ;\r\n");
      out.write("  color: Orange; \r\n");
      out.write("}\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"background:url(/vision/user/images/background/parquet_flooring-1920x1200.jpg); background-size: cover; \">\r\n");
      out.write("<table align=\"center\" width=\"80%\">\r\n");
      out.write(" <tr height=\"40\">\r\n");
      out.write("  <td>\r\n");
      out.write("  <a name=\"top\"></a>\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr height='50' >\r\n");
      out.write("  <td>\r\n");
      out.write("   <table id='indiv' align=\"center\"><!--table 2 inside table 1-->\r\n");
      out.write("     <tr>\r\n");
      out.write("\t  <td><a href='/vision/user/jsp files/index/index.jsp' target='_parent'>HOME</a></td>\r\n");
      out.write("      <td><a href='/vision/user/jsp files/index/about_us.jsp' target='_parent'>ABOUT US</a></td>\r\n");
      out.write("      <td><a href='/vision/user/jsp files/index/contact_us.jsp' target='_parent'>CONTACT US</a></td>\r\n");
      out.write("      <td><a href='/vision/user/jsp files/index/information.jsp' target='_top' class='current'>INFORMATION RESOURCE</a></td>\r\n");
      out.write("      <td><a href='/vision/user/jsp files/index/features.jsp' target='_parent'>FEATURES</a></td>\r\n");
      out.write("      <td><a href='/vision/user/jsp files/index/login_signup.jsp' target='_parent'>LOGIN/Sign Up</a></td>\r\n");
      out.write("                  \r\n");
      out.write("\t </tr>\t\t\t   \r\n");
      out.write("    </table><!--end of table 2-->                  \r\n");
      out.write("   </td>       \t            \r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr height='60'>\r\n");
      out.write("   <td>\r\n");
      out.write("   </td>\r\n");
      out.write("  </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("  <td align=\"center\">\r\n");
      out.write("  <img src='/vision/user/images/udaipur-city-map.jpg'>\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr height='60'>\r\n");
      out.write("  <td>\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("  <td>\r\n");
      out.write(" <p style=\"font-family: cursive;font-size: xx-large;font-weight: bold;color: Orange\">History Of Udaipur</p>\r\n");
      out.write("<p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\">Udaipur was founded in 1553 by Maharana Udai Singh II as the final capital of the erstwhile Mewar kingdom, located in the fertile circular valley-\"Girwa\" to the southwest of Nagda, on the Banas River, the first capital of the Mewar kingdom. This area already had a thriving trading town of \"Ayad\" which had served as capital of Mewar for over 200 years and 17 rulers of Mewar had ruled from Ayad town of Girwa Valley \r\n");
      out.write("Rawals ruled from Nagda; so the Girwa (& adjoining) valley was already well-known to Chittaud rulers who moved to it whenever the vulnerable tableland (Mesa)Chittaudgadh was threatened with enemy attacks.</p>\r\n");
      out.write("<p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\"> Maharana Udai Singh II, in the wake of 16th century emergence of artillery warfare decided to move his capital to a more secure location, importance of which he had realized during his exile at Kumbhalgadh. Ayad was flood-prone, hence he chose the ridge east of Pichola Lake to start his new capital city, where he came upon a hermit while hunting in the foothills of the Aravalli Range. The hermit blessed the king and asked him to build a palace on the spot, assuring him it would be well protected. Udai Singh II consequently established a residence on the site. In November 1567, the Mughal emperor Akbar attacked & laid siege of the venerated fort of Chittor, which was reduced to one of the 84 forts of Mewar.\r\n");
      out.write("</p>\r\n");
      out.write("<p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\">As the Mughal empire weakened, the Sisodia ranas, and later maharanas (also called the Guhilots or Suryavansh), who had always tried to oppose Mughal dominance, reasserted their independence and recaptured most of Mewar except for Chittor. Udaipur remained the capital of the state, which became a princely state of British India in 1818. Being a mountainous region and unsuitable for heavily armoured Mughal horses, Udaipur remained safe from Mughal influence in spite of much pressure. The rajvansh of Udaipur was one of the oldest dynasties of the world. Maharana Mahendra Singh Mewar (the Royal Family of Udaipur),is the current symbolic ruler of the city.\r\n");
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("<p style=\"font-family: cursive;font-size: xx-large;font-weight: bold;color: Orange\">About Udaipur</p>\r\n");
      out.write("<p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\">Udaipur is located 403 kilometers southeast from capital of the state Jaipur, Rajasthan and 250 kilometers from Ahmedabad, Gujarat. It is situated at the southern region of Rajasthan. Udaipur is truly an exquisite city with ample of natural splendor set at every nook and corner. It is amidst in the stunning Aravali Ranges of Rajasthan, India and known for its vivid fine-looking lakes, also called \"the city of lakes\". The captivating lakes in attendance everywhere make a flawless milieu around the city as well as sets upon many hues, colours and smiles on many people.\r\n");
      out.write("\r\n");
      out.write("This exotic city is full of palaces, temples and havelis present far and wide. The presence of greenery creates a sense of charm and harmony.</p> \r\n");
      out.write("\r\n");
      out.write("<p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\">It is famed for its heritage and culture around the globe and acts as a centre for the performing arts, painting and crafts. Udaipur is now looked upon and counted among the romantic cities of the World and subsequently called the \"Venice of East\".\r\n");
      out.write("\r\n");
      out.write("The famous \"white\" city of Rajasthan state, Udaipur has now become the talk of the town for all the people. It is unquestionably a dream destination for a romantic holiday. Its lakes being so fantabulous, exceptionally sets a place in our heart and are full of peace, calm and tranquility. Udaipur is a fascinating blend of sights, sounds and experiences - an inspiration for the imagination of the poets, painters and writers. It has not only lured the foreigners but both Hollywood and Bollywood, because of its scenic beauty. It has now become the fifty most dazzling city in the world but is marching on for more advancement.\r\n");
      out.write("</P>\r\n");
      out.write("<p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\">Udaipur is a popular tourist destination in India. The lakes, palaces and lively workspaces and culture attract foreign and domestic visitors. It is a favourite marriage destination. Many celebrities, including film stars, business families, politicians chose Udaipur to hold marriage ceremonies and parties. Udaipur have three interconnected lakes - the Fateh Sagar Lake, the Lake Pichhola and the smaller Swaroop Sagar Lake; along with forts, palaces, temples, gardens, mountains and narrow lanes lines withdrawn with stalls, relives the reminisces of a heroic past, valor and chivalry.\r\n");
      out.write("\r\n");
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("<p style=\"font-family: cursive;font-size: xx-large;font-weight: bold;color: Orange\">Geography and Climate of Udaipur</p>\r\n");
      out.write("<p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("Udaipur is located at 24.58Â°N 73.68Â°E at an average elevation of 598.00 m from the sea level. The climate of Udaipur is quite pleasant thus it makes it a perfect tourist destination. The tourism in Udaipur remains at peak from September to March.\r\n");
      out.write("\r\n");
      out.write("The Maximum temperature in summer ranges from 35 to 40 degrees Celsius and Minimum 21 to 26 degrees Celsius. Whereas in winters the Maximum temperature ranges between 21 to 25 degrees Celsius and a Minimum 5 to 11 degrees Celsius.\r\n");
      out.write("\r\n");
      out.write("The average rainfall (precipitation) of Udaipur is around 650 millimeters a year. The city experiences most of its rainfall in the months of July, August and September. The good rains in the season in its surrounding and catchment areas bring heavy inflow of water from various rives into its lakes. This in turns flourishes tourism business in Udaipur.\r\n");
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("<p style=\"font-family: cursive;font-size: xx-large;font-weight: bold;color: Orange\">Culture</p>\r\n");
      out.write("<p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\">Udaipur receives ample number of tourists from all over the world every year. The city is still inhabited by people of Bhil tribe, so you could see people dressed in typical Rajsthani dress with loads of silver jewelry during your trip.\r\n");
      out.write("Colorful festivals and fairs depict the cultural prosperity of Udaipur. The lakes, temples, huge forts and palaces boast about the rich legacy of this city. In this article, we have covered the subjects of people, cuisine, language, religion, folk dance and music of Udaipur.</p>\r\n");
      out.write("\r\n");
      out.write("<p style=\"color: White;font-family: cursive;font-size: x-large;text-align: justify;\">Cuisine</p>\r\n");
      out.write("<p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\">Udaipur cuisine comprises vegetarian dishes as the place is highly dominated by Jainism and Vaishnavism. Food is usually made from lots of vegetables and lentils. It is seasoned with a great variety of spices that are unique to the lands of Rajasthan. You can find type of curries ranging from Lentil to yoghurt.\r\n");
      out.write("Dried mango by the name of 'Ocra' and beans of 'sangri' is accompanied by many meals. Deep-fried breads and extensive use of chili makes the cuisine of Udaipur, a delicious one.</p> \r\n");
      out.write("\r\n");
      out.write("<p style=\"color: White;font-family: cursive;font-size: x-large;text-align: justify;\">People</p>\r\n");
      out.write("<p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\">Udaipur dwellers are really friendly and good to be with. On your first look, you will find them rugged, but these people are really good at heart. Untouched by the pace of modern times, these desert people are well-built, simple and cheerful.\r\n");
      out.write("Here, people usually prefer wearing bright colored clothes. The traditional attire of women is 'Ghaghra choli' (Skirt & blouse) and for men, angrakha (Kurta) and dhoti would do. In the modern times, people prefer wearing casual dress to match the contemporary fashion.</p> \r\n");
      out.write("\r\n");
      out.write("<p style=\"color: White;font-family: cursive;font-size: x-large;text-align: justify;\">Language</p>\r\n");
      out.write("<p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\">To communicate, language is really important. Mewari is the primary language of Udaipur, yet Rajasthani, Hindi and English are also common in the city.</p>\r\n");
      out.write("\r\n");
      out.write("<p style=\"color: White;font-family: cursive;font-size: x-large;text-align: justify;\">Religion</p>\r\n");
      out.write("<p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\">Jainism is the main religion which is observed in Udaipur. Other religions include Hinduism, Islam, Sikhism and Christianity in the decreasing order.</p>\r\n");
      out.write("\r\n");
      out.write("<p style=\"color: White;font-family: cursive;font-size: x-large;text-align: justify;\">Folk Dance and Music</p>\r\n");
      out.write("<p style=\"color: White;font-family: cursive;font-size: medium;text-align: justify;\">The dynamic and vibrant dance adds sparkle to this romantic city of Udaipur. Udaipur doesn't have its own dance that is especially linked with it. However, the dances that are famous all over Rajasthan make the dance of Udaipur too. \r\n");
      out.write("Bhavai, Ghoomar, Kachhi Ghodi, Kalbeliya and Terahtaali are the unusual dances of Rajasthan. Still, dance of Dandi Gair is associated with Marwar and hence with Udaipur. Talking about music, the dwellers of Udaipur find solace in the melodious music of Morchang, Naad, Tanpura, Sarangi and many other instruments that used to echo the courts of Mewar rulers.</p>\r\n");
      out.write("<a href='#top' style=\"color: Orange\">Back To Top</a>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
