/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2014-08-16 06:19:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user.jsp_0020files.hotels;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class hotels_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/user/jsp files/checksession.jsp", Long.valueOf(1407909381372L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");


String usernm = (String) session.getAttribute("username");
if(usernm==null)
	response.sendRedirect("/vision/user/jsp files/index/login_signup.jsp");

      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type='text/Javascript' src=\"/vision/user/js files/hotels.js\"></script><!--  for validation of category only -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".height\r\n");
      out.write(" {\r\n");
      out.write("  height:auto;\r\n");
      out.write(" }\r\n");
      out.write(" .textfield\r\n");
      out.write(" {\r\n");
      out.write("  font-size:18px;color:#000000;font-size:24px;     \r\n");
      out.write(" }\r\n");
      out.write(" .headtitle\r\n");
      out.write(" {\r\n");
      out.write("  font-family:sans-serif;font-size:24px;font-stretch:semi-expanded;font-weight:bold;color: Orange;\r\n");
      out.write(" }\r\n");
      out.write(" #loginhead\r\n");
      out.write(" {\r\n");
      out.write(" font-family:Geneva, Arial, Helvetica, sans-serif;font-size:36px;text-align:center; font-weight: bolder;\r\n");
      out.write(" }\r\n");
      out.write(" #categoryError\r\n");
      out.write(" {\r\n");
      out.write("  font-size:12px;color:#FF0000;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" input[type=submit],input[type=reset]\r\n");
      out.write(" {\r\n");
      out.write(" width: 40%;\r\n");
      out.write(" background-color:Black;\r\n");
      out.write(" margin-top: 35px;\r\n");
      out.write(" color: Orange;\r\n");
      out.write(" border: 2px solid Black;\r\n");
      out.write(" padding: 7px;\r\n");
      out.write(" font-size:20px;\r\n");
      out.write(" cursor:pointer;\r\n");
      out.write(" border-radius: 10px;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background:url(/vision/user/images/background/parquet_flooring-1920x1200.jpg) \">\r\n");
      out.write("<form id='hotels' method=\"post\" action=\"/vision/HotelSelectionServlet\">\r\n");
      out.write("<table align=\"center\" cellspacing=\"15\" cellpadding=\"0\" height=\"100%\" width=\"100%\">\r\n");
      out.write(" <tr height='40'>\r\n");
      out.write("  <td colspan=\"3\"></td>\r\n");
      out.write("  <td rowspan=\"6\">\r\n");
      out.write("   <iframe src=\"https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d29027.043714316354!2d73.68285879967506!3d24.57606258660182!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1sudaipur+hotels!5e0!3m2!1sen!2sin!4v1407515879663\" width=\"100%\" height=\"100%\" frameborder=\"0\" style=\"border:0\"></iframe>\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("  <td id='loginhead' colspan=\"3\" align=\"left\">UDAIPUR HOTELS</td>\r\n");
      out.write("  \r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr height='30' >\r\n");
      out.write("   <td colspan=\"3\"></td>\r\n");
      out.write("  </tr>\r\n");
      out.write(" \r\n");
      out.write(" <tr>\r\n");
      out.write("   <td class='height' width='300' align=\"center\"><span class='headtitle'>SELECT A CATEGORY:</span></td>\r\n");
      out.write("   <td ><select id='category' name='category'>\r\n");
      out.write("     <option value='Heritage Hotels'>Heritage Hotels</option>\r\n");
      out.write("     <option value='Luxury Hotels'>Luxury Hotels</option>\r\n");
      out.write("     <option value='Deluxe Hotels'>Deluxe Hotels</option>\r\n");
      out.write("     <option value='Budget Hotels'>Budget Hotels</option>\r\n");
      out.write("     \r\n");
      out.write("     <option value='' selected=\"selected\">---Select a Category---</option>\r\n");
      out.write("   </select></td>\r\n");
      out.write("   <td class='height' id='categoryError'>&nbsp; </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" \r\n");
      out.write(" <tr >\r\n");
      out.write("  <td  align=\"center\" class='height' width=\"300\"> \r\n");
      out.write("   <input type='submit' name='submit' value='Submit' id='submit' style=\"width: 200px;height: 50px\" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("  </td> \r\n");
      out.write("  <td  align=\"left\" class='height' width=\"300\">\r\n");
      out.write("   <input type='reset'  name='cancel' value='Cancel' id='reset' style=\"width: 200px;height: 50px\"/>\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr height='250'>\r\n");
      out.write("  <td>\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
